sql:
  db: makymono.db
telegram:
  token: 
twitter:
  consumer_key: 
  consumer_key_secret: 
  access_token: 
  access_token_secret: 
mastodon:
  consumer_key:
  consumer_key_secret:
  access_token:
  access_token_secret:

