db:
  type: 'sqlite'
  sqlite:
    filename: db/database.sqlite
telegram:
  token: TELEGRAM_TOKEN
  restrict_user: YOUR_USER_ID
twitter:
  enable: false
  consumer_key: TWITTER_CONSUMER_KEY
  consumer_key_secret: TWITTER_CONSUMER_KEY_SECRET
  access_token: TWITTER_ACCESS_TOKEN
  access_token_secret: TWITTER_ACCESS_TOKEN_SECRET
mastodon:
  enable: false
  api_base_url: https://mastodon.instance
  client_id: MASTODON_CLIENT_ID
  client_secret: MASTODON_CLIENT_SECRET
  access_token: MASTODON_ACCESS_TOKEN
  toot_visibility: unlisted
